# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.6


# Commands you want to run that will verify your build.
script: vendor/bin/phpunit